version: "3.1"

services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: portifolio
      MONGO_INITDB_ROOT_USERNAME: rick
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
