version: "3.1"

services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: portifolio
      MONGO_INITDB_ROOT_USERNAME: rick
      MONGO_INITDB_ROOT_PASSWORD: 533456
    ports:
      - 27018:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
